server:
  port: ${SERVER_PORT:9092}
  servlet:
    context-path: /flex-service/api/v1

ems:
  datasource:
    url: ${DATASOURCE_URL:jdbc:mariadb://localhost:3306/flexdb?allowPublicKeyRetrieval=true&useSSL=false}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: ${DATASOURCE_DRIVER:org.mariadb.jdbc.Driver}
    max-pool-size: 10


security:
  allow-credentials: true
  allowed-origins:
    - https://${CORS_DOMAIN}
    - http://localhost:4300
    - http://localhost:4200
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token

CRON-EXPRESSION: '*/10 * * * * *'